/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveTtcRouteImport } from './routes/live-ttc'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as RetreatsRouteImport } from './routes/retreats'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as LegalDocumentRouteImport } from './routes/legal.$document'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTtcRoute = LiveTtcRouteImport.update({
  id: '/live-ttc',
  path: '/live-ttc',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const RetreatsRoute = RetreatsRouteImport.update({
  id: '/retreats',
  path: '/retreats',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDocumentRoute = LegalDocumentRouteImport.update({
  id: '/legal/$document',
  path: '/legal/$document',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live-ttc': typeof LiveTtcRoute
  '/mentorship': typeof MentorshipRoute
  '/retreats': typeof RetreatsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/legal/$document': typeof LegalDocumentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live-ttc': typeof LiveTtcRoute
  '/mentorship': typeof MentorshipRoute
  '/retreats': typeof RetreatsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/legal/$document': typeof LegalDocumentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live-ttc': typeof LiveTtcRoute
  '/mentorship': typeof MentorshipRoute
  '/retreats': typeof RetreatsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/legal/$document': typeof LegalDocumentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/live-ttc'
    | '/mentorship'
    | '/retreats'
    | '/courses/$slug'
    | '/legal/$document'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/live-ttc'
    | '/mentorship'
    | '/retreats'
    | '/courses/$slug'
    | '/legal/$document'
  id:
    | '__root__'
    | '/'
    | '/live-ttc'
    | '/mentorship'
    | '/retreats'
    | '/courses/$slug'
    | '/legal/$document'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveTtcRoute: typeof LiveTtcRoute
  MentorshipRoute: typeof MentorshipRoute
  RetreatsRoute: typeof RetreatsRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  LegalDocumentRoute: typeof LegalDocumentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-ttc': {
      id: '/live-ttc'
      path: '/live-ttc'
      fullPath: '/live-ttc'
      preLoaderRoute: typeof LiveTtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retreats': {
      id: '/retreats'
      path: '/retreats'
      fullPath: '/retreats'
      preLoaderRoute: typeof RetreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$document': {
      id: '/legal/$document'
      path: '/legal/$document'
      fullPath: '/legal/$document'
      preLoaderRoute: typeof LegalDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveTtcRoute: LiveTtcRoute,
  MentorshipRoute: MentorshipRoute,
  RetreatsRoute: RetreatsRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  LegalDocumentRoute: LegalDocumentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
